workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
    - when: never

stages:
  - build

build:
  stage: build
  image: eclipse-temurin:21-jdk
  script:
    - chmod +x mvnw || true
    - ./mvnw -B clean test package
  artifacts:
    when: always
    paths:
      - target/*.jar
