stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

build:
  stage: build
  image: eclipse-temurin:21-jdk
  script:
    - chmod +x mvnw || true
    - ./mvnw -B clean test package
  artifacts:
    when: always
    paths:
      - target/*.jar
    expire_in: 1 week

dependency_check:
  stage: test
  image: eclipse-temurin:21-jdk
  needs: ["build"]
  script:
    - chmod +x mvnw || true
    - ./mvnw -B org.owasp:dependency-check-maven:check
  artifacts:
    when: always
    paths:
      - target/dependency-check-report.html
      - target/dependency-check-report.json
    expire_in: 1 week
