stages:
  - build
  - test

build:
  stage: build
  image: eclipse-temurin:21-jdk
  script:
    - chmod +x mvnw || true
    - ./mvnw -B clean test package
  artifacts:
    when: always
    paths:
      - target/*.jar

sast_semgrep:
  stage: test
  image: returntocorp/semgrep:latest
  needs: ["build"]
  script:
    - semgrep --config auto --sarif --output gl-sast-report.sarif || true
  artifacts:
    when: always
    reports:
      sast: gl-sast-report.sarif
    paths:
      - gl-sast-report.sarif
