name: build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:21-jdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build, test, package
        run: ./mvnw -B clean test package

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: ./target/*.jar
