name: build-and-dependency-check

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "task4", "sca-task4", "task4-depcheck" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: eclipse-temurin:21-jdk
    steps:
      - uses: actions/checkout@v4
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: Build
        run: ./mvnw -B clean test package

  dependency_check:
    runs-on: ubuntu-latest
    needs: build
    container: eclipse-temurin:21-jdk
    steps:
      - uses: actions/checkout@v4
      - name: Make mvnw executable
        run: chmod +x mvnw
      - name: OWASP Dependency-Check
        run: ./mvnw -B org.owasp:dependency-check-maven:check
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: |
            target/dependency-check-report.html
            target/dependency-check-report.json
